
function control_config(this_block)

  % Revision History:
  %
  %   24-Oct-2018  (13:35 hours):
  %     Original code was machine generated by Xilinx's System Generator after parsing
  %     C:\Users\abs105\Documents\MATLAB\control.v
  %
  %

  this_block.setTopLevelLanguage('Verilog');

  this_block.setEntityName('control');

  % System Generator has to assume that your entity  has a combinational feed through; 
  %   if it  doesn't, then comment out the following line:
  %this_block.tagAsCombinational;

  this_block.addSimulinkInport('opcode');

  this_block.addSimulinkOutport('regdst');
  this_block.addSimulinkOutport('branch');
  this_block.addSimulinkOutport('memread');
  this_block.addSimulinkOutport('memtoreg');
  this_block.addSimulinkOutport('memwrite');
  this_block.addSimulinkOutport('alusrc');
  this_block.addSimulinkOutport('regwrite');
  this_block.addSimulinkOutport('aluop');

  regdst_port = this_block.port('regdst');
  regdst_port.setType('UFix_1_0');
  regdst_port.useHDLVector(false);
  branch_port = this_block.port('branch');
  branch_port.setType('UFix_1_0');
  branch_port.useHDLVector(false);
  memread_port = this_block.port('memread');
  memread_port.setType('UFix_1_0');
  memread_port.useHDLVector(false);
  memtoreg_port = this_block.port('memtoreg');
  memtoreg_port.setType('UFix_1_0');
  memtoreg_port.useHDLVector(false);
  memwrite_port = this_block.port('memwrite');
  memwrite_port.setType('UFix_1_0');
  memwrite_port.useHDLVector(false);
  alusrc_port = this_block.port('alusrc');
  alusrc_port.setType('UFix_1_0');
  alusrc_port.useHDLVector(false);
  regwrite_port = this_block.port('regwrite');
  regwrite_port.setType('UFix_1_0');
  regwrite_port.useHDLVector(false);
  aluop_port = this_block.port('aluop');
  aluop_port.setType('UFix_2_0');

  % -----------------------------
  if (this_block.inputTypesKnown)
    % do input type checking, dynamic output type and generic setup in this code block.

    if (this_block.port('opcode').width ~= 6);
      this_block.setError('Input data type for port "opcode" must have width=6.');
    end

  end  % if(inputTypesKnown)
  % -----------------------------

  % System Generator found no apparent clock signals in the HDL, assuming combinational logic.
  % -----------------------------
   if (this_block.inputRatesKnown)
     inputRates = this_block.inputRates; 
     uniqueInputRates = unique(inputRates); 
     outputRate = uniqueInputRates(1);
     for i = 2:length(uniqueInputRates)
       if (uniqueInputRates(i) ~= Inf)
         outputRate = gcd(outputRate,uniqueInputRates(i));
       end
     end  % for(i)
     for i = 1:this_block.numSimulinkOutports 
       this_block.outport(i).setRate(outputRate); 
     end  % for(i)
   end  % if(inputRatesKnown)
  % -----------------------------

    % (!) Set the inout port rate to be the same as the first input 
    %     rate. Change the following code if this is untrue.
    uniqueInputRates = unique(this_block.getInputRates);


  % Add addtional source files as needed.
  %  |-------------
  %  | Add files in the order in which they should be compiled.
  %  | If two files "a.vhd" and "b.vhd" contain the entities
  %  | entity_a and entity_b, and entity_a contains a
  %  | component of type entity_b, the correct sequence of
  %  | addFile() calls would be:
  %  |    this_block.addFile('b.vhd');
  %  |    this_block.addFile('a.vhd');
  %  |-------------

  %    this_block.addFile('');
  %    this_block.addFile('');
  this_block.addFile('control.v');

return;


