
function datamem_config(this_block)

  % Revision History:
  %
  %   24-Oct-2018  (14:11 hours):
  %     Original code was machine generated by Xilinx's System Generator after parsing
  %     C:\Users\abs105\Documents\MATLAB\datamem.v
  %
  %

  this_block.setTopLevelLanguage('Verilog');

  this_block.setEntityName('datamem');

  % System Generator has to assume that your entity  has a combinational feed through; 
  %   if it  doesn't, then comment out the following line:
 % this_block.tagAsCombinational;

  this_block.addSimulinkInport('memwrite');
  this_block.addSimulinkInport('memread');
  this_block.addSimulinkInport('addr');
  this_block.addSimulinkInport('wrdata');

  this_block.addSimulinkOutport('rdata');

  rdata_port = this_block.port('rdata');
  rdata_port.setType('UFix_32_0');

  % -----------------------------
  if (this_block.inputTypesKnown)
    % do input type checking, dynamic output type and generic setup in this code block.

    if (this_block.port('memwrite').width ~= 1);
      this_block.setError('Input data type for port "memwrite" must have width=1.');
    end

    this_block.port('memwrite').useHDLVector(false);

    if (this_block.port('memread').width ~= 1);
      this_block.setError('Input data type for port "memread" must have width=1.');
    end

    this_block.port('memread').useHDLVector(false);

    if (this_block.port('addr').width ~= 32);
      this_block.setError('Input data type for port "addr" must have width=32.');
    end

    if (this_block.port('wrdata').width ~= 32);
      this_block.setError('Input data type for port "wrdata" must have width=32.');
    end

  end  % if(inputTypesKnown)
  % -----------------------------

  % -----------------------------
   if (this_block.inputRatesKnown)
     setup_as_single_rate(this_block,'clk','ce')
   end  % if(inputRatesKnown)
  % -----------------------------

    % (!) Set the inout port rate to be the same as the first input 
    %     rate. Change the following code if this is untrue.
    uniqueInputRates = unique(this_block.getInputRates);


  % Add addtional source files as needed.
  %  |-------------
  %  | Add files in the order in which they should be compiled.
  %  | If two files "a.vhd" and "b.vhd" contain the entities
  %  | entity_a and entity_b, and entity_a contains a
  %  | component of type entity_b, the correct sequence of
  %  | addFile() calls would be:
  %  |    this_block.addFile('b.vhd');
  %  |    this_block.addFile('a.vhd');
  %  |-------------

  %    this_block.addFile('');
  %    this_block.addFile('');
  this_block.addFile('datamem.v');

return;


% ------------------------------------------------------------

function setup_as_single_rate(block,clkname,cename) 
  inputRates = block.inputRates; 
  uniqueInputRates = unique(inputRates); 
  if (length(uniqueInputRates)==1 & uniqueInputRates(1)==Inf) 
    block.addError('The inputs to this block cannot all be constant.'); 
    return; 
  end 
  if (uniqueInputRates(end) == Inf) 
     hasConstantInput = true; 
     uniqueInputRates = uniqueInputRates(1:end-1); 
  end 
  if (length(uniqueInputRates) ~= 1) 
    block.addError('The inputs to this block must run at a single rate.'); 
    return; 
  end 
  theInputRate = uniqueInputRates(1); 
  for i = 1:block.numSimulinkOutports 
     block.outport(i).setRate(theInputRate); 
  end 
  block.addClkCEPair(clkname,cename,theInputRate); 
  return; 

% ------------------------------------------------------------

