
function instrmem_config(this_block)

  % Revision History:
  %
  %   24-Oct-2018  (13:33 hours):
  %     Original code was machine generated by Xilinx's System Generator after parsing
  %     C:\Users\abs105\Documents\MATLAB\instrmemo.v
  %
  %

  this_block.setTopLevelLanguage('Verilog');

  this_block.setEntityName('instrmem');

  % System Generator has to assume that your entity  has a combinational feed through; 
  %   if it  doesn't, then comment out the following line:
  %this_block.tagAsCombinational;

  this_block.addSimulinkInport('pcread');

  this_block.addSimulinkOutport('opcode');
  this_block.addSimulinkOutport('func');
  this_block.addSimulinkOutport('rs');
  this_block.addSimulinkOutport('rt');
  this_block.addSimulinkOutport('rd');
  this_block.addSimulinkOutport('imm');

  opcode_port = this_block.port('opcode');
  opcode_port.setType('UFix_6_0');
  func_port = this_block.port('func');
  func_port.setType('UFix_6_0');
  rs_port = this_block.port('rs');
  rs_port.setType('UFix_5_0');
  rt_port = this_block.port('rt');
  rt_port.setType('UFix_5_0');
  rd_port = this_block.port('rd');
  rd_port.setType('UFix_5_0');
  imm_port = this_block.port('imm');
  imm_port.setType('UFix_16_0');

  % -----------------------------
  if (this_block.inputTypesKnown)
    % do input type checking, dynamic output type and generic setup in this code block.

    if (this_block.port('pcread').width ~= 32);
      this_block.setError('Input data type for port "pcread" must have width=32.');
    end

  end  % if(inputTypesKnown)
  % -----------------------------

  % System Generator found no apparent clock signals in the HDL, assuming combinational logic.
  % -----------------------------
   if (this_block.inputRatesKnown)
     inputRates = this_block.inputRates; 
     uniqueInputRates = unique(inputRates); 
     outputRate = uniqueInputRates(1);
     for i = 2:length(uniqueInputRates)
       if (uniqueInputRates(i) ~= Inf)
         outputRate = gcd(outputRate,uniqueInputRates(i));
       end
     end  % for(i)
     for i = 1:this_block.numSimulinkOutports 
       this_block.outport(i).setRate(outputRate); 
     end  % for(i)
   end  % if(inputRatesKnown)
  % -----------------------------

    % (!) Set the inout port rate to be the same as the first input 
    %     rate. Change the following code if this is untrue.
    uniqueInputRates = unique(this_block.getInputRates);


  % Add addtional source files as needed.
  %  |-------------
  %  | Add files in the order in which they should be compiled.
  %  | If two files "a.vhd" and "b.vhd" contain the entities
  %  | entity_a and entity_b, and entity_a contains a
  %  | component of type entity_b, the correct sequence of
  %  | addFile() calls would be:
  %  |    this_block.addFile('b.vhd');
  %  |    this_block.addFile('a.vhd');
  %  |-------------

  %    this_block.addFile('');
  %    this_block.addFile('');
  this_block.addFile('instrmemo.v');

return;


